version: '2'

networks: 
  ascd:

services: #컨테이너 서비스 
  ca.maluser1.ascdpub.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.maluser1.ascdpub.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.maluser1.ascdpub.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/38dab01f4395c77cdac6dcd100eeaef32719030a0747c00157ef589da5a88d3b_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/maluser1.ascdpub.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.maluser1.ascdpub.com
    networks:
      - ascd